# Generated by Django 5.1.3 on 2025-04-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_withdrawalrequest_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.FloatField(),
        ),
    ]
