# Generated by Django 5.1.3 on 2025-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_withdrawal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorearnings',
            name='available_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='creatorearnings',
            name='total_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paypaltransaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
