# Generated by Django 5.1.3 on 2025-04-24 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_creatorearnings_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='payment_for',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
