# Generated by Django 5.1.3 on 2025-04-24 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paypaltransaction_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='active_duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
