# Generated by Django 5.1.3 on 2025-04-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paypaltransaction_active_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypaltransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='paypaltransaction',
            name='is_status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paypaltransaction',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
