# Generated by Django 5.1.3 on 2025-04-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
