# Generated by Django 5.1.3 on 2025-06-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_withdrawn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='background_profile_pics/'),
        ),
    ]
