# Generated by Django 5.1.3 on 2025-06-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_background_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_account_id',
        ),
    ]
