# Generated by Django 5.1.3 on 2025-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='age_rating',
            field=models.IntegerField(default='0'),
        ),
    ]
