# Generated by Django 5.1.3 on 2025-03-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('short_film', 'Short Film'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('entertainment', 'Entertainment Project'), ('music', 'Music'), ('education', 'Education'), ('interviews', 'Interviews'), ('animation', 'Animation'), ('web_series', 'Web Series')], max_length=50),
        ),
    ]
