# Generated by Django 5.1.3 on 2025-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_collaborate_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(default='Not Mentioned', max_length=200),
        ),
    ]
