# Generated by Django 5.1.3 on 2025-04-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_content_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
