# Generated by Django 5.1.3 on 2025-05-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_content_is_premium_content_preview_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='ads/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='collaborate',
            name='content_type',
            field=models.CharField(choices=[('short_film', 'Short Film'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('entertainment', 'Entertainment Project'), ('music', 'Music'), ('education', 'Education'), ('interviews', 'Interviews'), ('animation', 'Animation'), ('web_series', 'Web Series'), ('short_series', 'Short Series'), ('drama', 'Drama'), ('shorts', 'Shorts'), ('web_shorts', 'Web Shorts'), ('feature_series', 'Feature Series')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('short_film', 'Short Film'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('entertainment', 'Entertainment Project'), ('music', 'Music'), ('education', 'Education'), ('interviews', 'Interviews'), ('animation', 'Animation'), ('web_series', 'Web Series'), ('short_series', 'Short Series'), ('drama', 'Drama'), ('shorts', 'Shorts'), ('web_shorts', 'Web Shorts'), ('feature_series', 'Feature Series')], max_length=50),
        ),
    ]
