# Generated by Django 5.1.3 on 2025-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_ad_active_remove_ad_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='video_url',
            field=models.FileField(upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Magic', 'Magic'), ('Poem', 'Poem'), ('History', 'History'), ('Epic', 'Epic'), ('Health', 'Health'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French'), ('Russian', 'Russian'), ('German', 'German'), ('Spanish', 'Spanish'), ('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Regional_language', 'Regional_language')], max_length=50),
        ),
    ]
