# Generated by Django 5.1.3 on 2025-06-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_ad_video_url_alter_content_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('short_film', 'Short Film'), ('podcast', 'Podcast'), ('documentary', 'Documentary'), ('entertainment', 'Entertainment Project'), ('music', 'Music'), ('education', 'Education'), ('interviews', 'Interviews'), ('animation', 'Animation'), ('web_series', 'Web Series'), ('short_series', 'Short Series'), ('drama', 'Drama'), ('shorts', 'Shorts'), ('web_shorts', 'Web Shorts'), ('feature_series', 'Feature Series'), ('stand_up', 'Stand Up Comedy'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.CharField(choices=[('English', 'English'), ('Indian', 'Indian'), ('French', 'French'), ('Russian', 'Russian'), ('German', 'German'), ('Spanish', 'Spanish'), ('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Magic', 'Magic'), ('Poem', 'Poem'), ('History', 'History'), ('Epic', 'Epic'), ('Health', 'Health'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French'), ('Russian', 'Russian'), ('German', 'German'), ('Spanish', 'Spanish'), ('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Regional_language', 'Regional_language'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='preview_duration',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
